services:

  # This service stores aggregated quality indicator results submitted
  # by different data providers.
  database:
    build: database
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - database-password
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql
    networks:
      - database

  # This service receives aggregated quality indicator results from
  # data providers and answers queries for quality indicator results.
  data-exchange:
    image: ghcr.io/umg-minai/indicate-data-exchange-server:1.1.0
    restart: unless-stopped
    env_file: database.env
    environment:
      DATABASE_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - database-password
    networks:
      - database
    ports:
      - 8080:8080
    depends_on:
      - database

secrets:
  database-password:
    file: database-password

volumes:
  data:
    external: no

networks:
  database:
    external: no
